name: CI
on:
  push:
    branches:
      - master
      - dev
  pull_request : {}

jobs:
  test_ubuntu_macos:
    name: Test on Julia ${{ matrix.julia-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.9', '1.11']
        os: ['ubuntu-latest', 'macOS-latest']
    steps:
      - uses: actions/checkout@v4
      # Set up PyCall
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      #   pyscf 2.3.0 on GitHub cannot be built :(
      # Julia Tasks
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: 'x64'
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON : ""
      - name: Setup Conda.jl and install pyscf 2.4.0
        run: julia -e 'using Pkg; Pkg.add("Conda"); using Conda; Conda.pip_interop(true); Conda.pip("install", "pyscf==2.4.0")'
      - uses: julia-actions/julia-runtest@v1
        with:
          annotate: true
      - uses: julia-actions/julia-processcoverage@v1

  test_windows:
    name: Test on Julia ${{ matrix.julia_version }} - windows-latest
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        julia_version: ['1.9', '1.11']
    steps:
      - uses: actions/checkout@v4
      # Set up PyCall
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      # Julia Tasks
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia_version }}
          arch: 'x64'
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON : "python"
      - uses: julia-actions/julia-runtest@v1
        with:
          annotate: true
          test_args: 'no-pyscf'
      - uses: julia-actions/julia-processcoverage@v1